[package]
name = "ai"
version = "0.1.0"
edition = "2024"

[dependencies]
anthropic = { path = "../anthropic" }
gemini = { path = "../gemini" }
openai = { path = "../openai" }
provider = { path = "../provider" }
xai = { path = "../xai" }
