[package]
name = "provider"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
futures = "0.3.31"
iana-media-types = "0.1.2"
schemars = "1.1.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[lints]
workspace = true
