[package]
name = "openai"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
provider = { path = "../provider" }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
